// <auto-generated />
using System;
using DroneKurye.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DroneKurye.src.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522100342_UpdateAdminSeed")]
    partial class UpdateAdminSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("DroneKurye.Models.Advertisement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("DroneKurye.Models.DeliveryOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DestinationLat")
                        .HasColumnType("REAL");

                    b.Property<double>("DestinationLng")
                        .HasColumnType("REAL");

                    b.Property<double?>("DroneLat")
                        .HasColumnType("REAL");

                    b.Property<double?>("DroneLng")
                        .HasColumnType("REAL");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("VehicleLat")
                        .HasColumnType("REAL");

                    b.Property<double?>("VehicleLng")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("DeliveryOrders");
                });

            modelBuilder.Entity("DroneKurye.Models.DroneDataHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AccelerationX")
                        .HasColumnType("REAL");

                    b.Property<double>("AccelerationY")
                        .HasColumnType("REAL");

                    b.Property<double>("AccelerationZ")
                        .HasColumnType("REAL");

                    b.Property<double>("Altitude")
                        .HasColumnType("REAL");

                    b.Property<bool>("BaseStationConnected")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BaseStationDistance")
                        .HasColumnType("REAL");

                    b.Property<int>("BatteryPercent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CameraOk")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlightMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("GpsConnected")
                        .HasColumnType("INTEGER");

                    b.Property<double>("GyroscopeX")
                        .HasColumnType("REAL");

                    b.Property<double>("GyroscopeY")
                        .HasColumnType("REAL");

                    b.Property<double>("GyroscopeZ")
                        .HasColumnType("REAL");

                    b.Property<string>("HmsMessages")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("MotorRpms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MotorsOk")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ObstacleDetected")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Pitch")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Roll")
                        .HasColumnType("REAL");

                    b.Property<string>("RtkStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SignalStrength")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Speed")
                        .HasColumnType("REAL");

                    b.Property<int>("WindLevel")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Yaw")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("DroneDataHistory");
                });

            modelBuilder.Entity("DroneKurye.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DroneKurye.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("DroneKurye.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IyzicoSubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("DroneKurye.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@dronekurye.com",
                            FullName = "Sistem Yöneticisi",
                            IsActive = true,
                            PasswordHash = "$2a$11$92qlBGHrxEBDPSGDMonlgOqnHyAKAEjRFhgcCkHuBdVBbk16aXNUu",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("DroneKurye.Models.Notification", b =>
                {
                    b.HasOne("DroneKurye.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("DroneKurye.Models.RefreshToken", b =>
                {
                    b.HasOne("DroneKurye.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DroneKurye.Models.Subscription", b =>
                {
                    b.HasOne("DroneKurye.Models.User", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("DroneKurye.Models.Subscription", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DroneKurye.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
